# Güzellik Haritam - Codemagic Build Configuration
workflows:
  ios-release:
    name: Güzellik Haritam iOS Release
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      groups:
        # Codemagic panelinde "Environment Variables" kısmında 
        # 'apple_credentials' isimli bir grup oluşturup değişkenleri eklemiş olmalısınız.
        - apple_credentials
      vars:
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        # APP_ID: App Store Connect -> Uygulamanız -> Uygulama Bilgileri -> Apple Kimliği (10 haneli rakam)
        APP_ID: 6758340475 
      flutter: 3.10.4
      xcode: latest
      cocoapods: default

    scripts:
      - name: Bağımlılıklar ve Kod Üretimi (Build Runner)
        script: | 
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs
      
      - name: CocoaPods Yükleme
        script: | 
          cd ios && pod install
      
      - name: Anahtarlık Başlatma (Keychain)
        script: | 
          keychain initialize
      
      - name: Apple Sertifikalarını Getir (Signing)
        script: | 
          # Bu komut sertifikaları Apple'dan otomatik çeker
          app-store-connect fetch-signing-files "com.emx.guzellikharitam" --type IOS_APP_STORE --create
          keychain add-certificates
      
      - name: Flutter iOS Build
        script: | 
          # .ipa oluşturmak için ön hazırlık build'i
          flutter build ios --release --build-number=$BUILD_NUMBER --no-codesign
      
      - name: Xcode Arşivleme ve IPA Oluşturma
        script: | 
          # Uygulamayı imzalar ve gönderilebilir IPA dosyasını paketler
          xcode-project build-ipa --workspace "$XCODE_WORKSPACE" --scheme "$XCODE_SCHEME"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect:
        auth: integration
        # Uygulama başarıyla yüklendiğinde TestFlight'a gönderir
        submit_to_testflight: true
