workflows:
  ios-simulator-build:
    name: iOS Simulator Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    
    scripts:
      # Flutter SDK'yı hazırla
      - name: Flutter sürümünü kontrol et
        script: |
          flutter --version
          flutter doctor -v
      
      # Bağımlılıkları yükle
      - name: Flutter bağımlılıklarını yükle
        script: |
          flutter pub get
      
      # iOS dizinine geç ve CocoaPods kurulumu
      - name: CocoaPods bağımlılıklarını yükle
        script: |
          cd ios && pod install --repo-update
      
      # iOS Simulator için build
      - name: iOS Simulator için build al
        script: |
          flutter build ios --simulator --debug
      
      # .app dosyasını hazırla
      - name: Simulator .app dosyasını kopyala
        script: |
          cd build/ios/iphonesimulator
          mkdir -p $CM_BUILD_OUTPUT_DIR
          cp -r Runner.app $CM_BUILD_OUTPUT_DIR/
    
    artifacts:
      - build/ios/iphonesimulator/Runner.app
      - $CM_BUILD_OUTPUT_DIR/*.app
      - flutter_drive.log
    
    publishing:
      email:
        recipients:
          - emirtanir55@gmail.com  # E-posta adresinizi buraya yazın
        notify:
          success: true
          failure: true