# Güzellik Haritam - Codemagic Build Configuration
workflows:
  ios-release:
    name: Güzellik Haritam iOS Release
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      groups:
        # Codemagic panelinde 'apple_credentials' grubunu oluşturmuş olmalısınız.
        - apple_credentials
      vars:
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        # BURAYI GÜNCELLEYİN: App Store Connect'teki 10 haneli Apple ID'niz
        APP_ID: 6758340475 
      flutter: 3.10.4
      xcode: latest
      cocoapods: default

    scripts:
      - name: Bağımlılıklar ve Kod Üretimi (Build Runner)
        script: | 
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs
      
      - name: CocoaPods Yükleme
        script: | 
          cd ios && pod install
      
      - name: Anahtarlık Başlatma (Keychain)
        script: | 
          keychain initialize
      
      - name: Apple Sertifikalarını Getir (Signing)
        script: | 
          # Sertifikaları Apple sunucularından çeker
          app-store-connect fetch-signing-files "com.emx.guzellikharitam" \
            --issuer-id $APP_STORE_CONNECT_ISSUER_ID \
            --key-id $APP_STORE_CONNECT_KEY_IDENTIFIER \
            --private-key $APP_STORE_CONNECT_PRIVATE_KEY \
            --type IOS_APP_STORE \
            --create
          keychain add-certificates
      
      - name: Flutter iOS Build
        script: | 
          flutter build ios --release --build-number=$BUILD_NUMBER --no-codesign
      
      - name: Xcode Arşivleme ve IPA Oluşturma
        script: | 
          xcode-project build-ipa --workspace "$XCODE_WORKSPACE" --scheme "$XCODE_SCHEME"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect:
        # Codemagic'in zorunlu tuttuğu 3 anahtar:
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        # Uygulama başarıyla yüklendiğinde TestFlight'a gönderir
        submit_to_testflight: true
