scripts:
  - name: Build iOS app for Appetize
    script: |
      flutter build ios --simulator
      mkdir -p artifacts
      cp -R build/ios/iphonesimulator/*.app artifacts/
artifacts:
  - artifacts/*.app